# See https://openmod.github.io/openmod-docs/devdoc/concepts/configuration.html
# You can delete this file if you do not need a configuration

database:
  ConnectionStrings:
    default: "Server=192.168.178.232; Database=unturned; Port=3306; User=unturned; Password=unturned"